#EXEC ONCE
# exec-once= ~/.config/hypr/scripts/hyprland_execs_once.sh

exec-once=touch /tmp/hyprstart.lock # lock file used to avoid running the hyprland_reload.sh script the first time

# UI Related Stuff #
exec-once = swww-daemon --format xrgb; # weird fix but ok 
exec-once= swww img $XDG_CONFIG_HOME/Wallpapers/$(wpg -c)

#bar 
exec-once=waybar 
exec-once=swaync -c .config/swaync/config.json -s .config/swaync/style.css 

# Daemons and BG apps #
exec-once=~/.config/hypr/scripts/xdg-portal-reset.sh
exec-once=udiskie &
exec-once=pywalfox start
exec-once=nm-applet --indicator & 
exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store

exec-once=calcurse --daemon & 
exec-once=syncthing-gtk --minimized & 


# Audio n Music Stuff #
exec-once=playerctld daemon 
exec-once=spotify 
exec-once=mpd 
exec-once=mpDris2 
exec-once=spicetify watch -s
exec-once= mpc random on && mpc play || mpc insert Chill/Somewhere\ Nowhere\ 🌸Deep\ Lofi\ Beats.mp3 && mpc next && mpc toggle && mpc toggle


# Auto launch Apps i like #
exec-once=obsidian 
exec-once=[group] vesktop --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
exec-once=[group] easyeffects 
exec-once=[group] spotify 
exec-once=[group] librewolf 
exec-once=[group] keepassxc 

exec-once = hyprpm reload -n

# Reload script that updates themes and everything #
exec= ~/.config/hypr/scripts/hyprland_reload.sh
