#EXEC ONCE
# exec-once= ~/.config/hypr/scripts/hyprland_execs_once.sh

exec-once=touch /tmp/hyprstart.lock

exec-once=waybar

exec-once=sleep 1; swww init 

exec-once=swaync -c .config/swaync/config.json -s .config/swaync/style.css & 

exec-once=swww img /home/traveler/Imagens/$(wpg -c)

exec-once=./scripts/xdg-portal.sh
exec-once=nm-applet --indicator 
exec-once=calcurse-daemon
exec-once=syncthing-gtk --minimized

exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store

exec-once=obsidian
exec-once=[group] vencord-desktop --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --disable-gpu --no-sandbox
exec-once=[group] easyeffects
exec-once=[group] spotify
exec-once=[group] librewolf 
exec-once=[group] keepassxc 


exec-once=playerctld daemon 
exec-once=spotify 
exec-once=mpd 
exec-once=mpDris2 
exec-once= mpc random on && mpc play || mpc insert Chill/Somewhere\ Nowhere\ 🌸Deep\ Lofi\ Beats.mp3 && mpc next && mpc toggle && mpc toggle


#EXECS
exec= ~/.config/hypr/scripts/hyprland_reload.sh
