# Dynamic Hyprland Style settings, modified by wpgtk

general {

    gaps_in=5
    gaps_out=20
    border_size=1
    col.active_border= rgb(f04c6e) rgb(e97bb9) 
    col.inactive_border=rgb(231d2d)

}

decoration {

	blur {
		enabled= false
		size=4 # minimum 1
		passes=1 # minimum 1
		new_optimizations=1
	}

    rounding=7
    drop_shadow=true
    shadow_range=10
    col.shadow=rgb(AD475C)
    col.shadow_inactive = rgb(0C0A0F)

}

group {
	
	col.border_inactive= rgba(0C0A0F00)
    col.border_active= rgb(e97bb9) rgb(f04c6e) 
		groupbar {
			col.inactive=rgba(0C0A0F00)
			col.active= rgb(e97bb9) rgb(f04c6e) 
			font_size = 12
			text_color = rgb(fff1f8)
			gradients = true 
			render_titles= true
		}

	}
plugin {
    hyprbars {
        # example config
		bar_precedence_over_border=true
        bar_height = 24
		bar_title_enabled = true
		bar_color= rgb(0C0A0F)
		col.text = rgb(f04c6e)
		bar_text_font=ShureTechMono Nerd Font Mono
		bar_part_of_window = true
		bar_button_padding=12
        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(f04c6e),14,, hyprctl dispatch killactive
        hyprbars-button = rgb(f04c6e),14,󰊓, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(f04c6e),14,󰐃, hyprctl dispatch pin



    }
}
