# Dynamic Hyprland Style settings, modified by wpgtk

general {

    gaps_in=4
    gaps_out=16,16,16,16
    border_size=1
    col.active_border= rgb(4585ff) rgb(5f71df) 
    col.inactive_border=rgb(120f39)

}

decoration {

	blur {
		enabled= false
		size=4 # minimum 1
		passes=1 # minimum 1
		new_optimizations=1
	}

    rounding=10
    drop_shadow=false
    shadow_range=4
    col.shadow=rgb(436CCE)
    col.shadow_inactive = rgb(060511)

}

group {
	
	col.border_inactive= rgba(06051100)
    col.border_active= rgb(5f71df) rgb(4585ff) 
		groupbar {
			col.inactive=rgba(06051100)
			col.active= rgb(5f71df) rgb(4585ff) 
			font_size = 12
			text_color = rgb(f6f2ff)
			gradients =false 
			render_titles= true
		}

	}
plugin {
    hyprbars {
        # example config
		bar_precedence_over_border=true
        bar_height = 24
		bar_title_enabled = true
		bar_color= rgb(060511)
		col.text = rgb(4585ff)
		bar_text_font=ShureTechMono Nerd Font Mono
		bar_part_of_window = true
		bar_button_padding=12
        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(4585ff),14,, hyprctl dispatch killactive
        hyprbars-button = rgb(4585ff),14,󰊓, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(4585ff),14,󰐃, hyprctl dispatch pin



    }
}
