# Dynamic Hyprland Style settings, modified by wpgtk

general {

    gaps_in=4
    gaps_out=16,16,16,16
    border_size=1
    col.active_border= rgb(b94266)
    col.inactive_border=rgb(152447)

}

decoration {

	blur {
		enabled= false
		size=4 # minimum 1
		passes=1 # minimum 1
		new_optimizations=1
	}

    rounding=10
    drop_shadow=true
	shadow_offset=4 4
    shadow_range=0
    col.shadow=rgb(b94266)
	shadow_render_power=1
    col.shadow_inactive = rgb(152447)

}

group {
	
	col.border_inactive= rgba(080C1500)
    col.border_active= rgb(e05486) rgb(b94266) 
		groupbar {
			col.inactive=rgba(080C1500)
			col.active= rgb(e05486) rgb(b94266) 
			font_size = 12
			font_family=ShureTechMono Nerd Font Mono Bold
			text_color = rgb(ffdbfd)
			gradients =false 
			render_titles= true
		}

	}
plugin {
    hyprbars {
        # example config
		bar_precedence_over_border=true
        bar_height = 24
		bar_title_enabled = true
		bar_color= rgb(080C15)
		col.text = rgb(b94266)
		bar_text_font=ShureTechMono Nerd Font Mono
		bar_part_of_window = true
		bar_button_padding=12
        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(b94266),14,, hyprctl dispatch killactive
        hyprbars-button = rgb(b94266),14,󰊓, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(b94266),14,󰐃, hyprctl dispatch pin



    }
}
