[default]
font0 = Mononoki Nerd Font
opacity = 1
blur_size = 4
pad = 10
f_small = 12
f_big = 20
b_radius = 10
b_radius2 = 7
b_size = 1
font1 = ShureTechMono Nerd Font Mono
font_size = 9
gaps_out = 20
blur = false

