[default]
font0 = SauceCodePro Nerd Font Mono:style=Bold
opacity = 1
blur_size = 5
pad = 10
f_small = 12
f_big = 20
b_radius = 20
b_radius2 = 15
b_size = 2
font1 = ShureTechMono Nerd Font Mono
font_size = 9

