[default]
font0 = Mononoki Nerd Font Mono:style=Bold
opacity = 1
blur_size = 2
pad = 10
f_small = 12
f_big = 20
b_radius = 10
b_radius2 = 7
b_size = 2
font1 = ShureTechMono Nerd Font Mono
font_size = 9
gaps_out = 16

