[settings]
set_wallpaper = false
gtk = true
active = 1
light_theme = false
editor = kitty -e lvim
execute_cmd = false
command = hyprctl reload
backend = wal
alpha = 100
smart_sort = false
auto_adjust = false
reload = false
keywords = default
vte = true

[keywords]

