[settings]
set_wallpaper = false
gtk = false
active = 1
light_theme = false
editor = kitty -e lvim
execute_cmd = true
command = hyprctl reload
backend = wal
alpha = 100
smart_sort = false
auto_adjust = true
reload = false
keywords = default
vte = false

[keywords]

